version: '3.8'

services:
  whatsapp-api:
    image: ghcr.io/peter-hanzo/wweb-mcp@sha256:597e473cdcc0b7333d7fd0c4b79a6670c1beb40087ef8de8c3e7b79372e3cd36
    container_name: whatsapp-api
    environment:
      - MODE=whatsapp-api            # исправлено на правильный режим
      - API_PORT=${API_PORT:-5001}   # дефолт 5001
      - API_KEY=${API_KEY:-default-api-key}
    ports:
      - "${API_PORT:-5001}:${API_PORT:-5001}"
    volumes:
      - whatsapp_auth_data:/wwebjs_auth    # монтируем папку с auth-данными
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT:-5001}/api/health"]  # простой healthcheck
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - dokploy-network

  whatsapp-mcp:
    image: ghcr.io/peter-hanzo/wweb-mcp@sha256:597e473cdcc0b7333d7fd0c4b79a6670c1beb40087ef8de8c3e7b79372e3cd36
    container_name: whatsapp-mcp
    environment:
      - MODE=mcp
      - TRANSPORT=${TRANSPORT:-sse}
      - SSE_PORT=${SSE_PORT:-5002}
      - API_BASE_URL=http://whatsapp-api:${API_PORT:-5001}/api
      - API_KEY=${API_KEY:-default-api-key}
    ports:
      - "${SSE_PORT:-5002}:${SSE_PORT:-5002}"
    depends_on:
      whatsapp-api:
        condition: service_healthy   # ждем готовности API
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  whatsapp_auth_data:

networks:
  dokploy-network:
    driver: bridge
