version: "3.8"

services:
  whatsapp-api:
    image: ghcr.io/peter-hanzo/wweb-mcp:latest
    container_name: whatsapp-api
    environment:
      - MODE=whatsapp-api
      - API_KEY=${API_KEY}
    command: >
      sh -c "node dist/main.js \
        --mode whatsapp-api \
        --api-port 5001"
    ports:
      - "5001:5001"
    volumes:
      - whatsapp_api_auth:/app/.wwebjs_auth
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/api/health || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - dokploy-network

  whatsapp-mcp:
    image: ghcr.io/peter-hanzo/wweb-mcp:latest
    container_name: whatsapp-mcp
    environment:
      - MODE=mcp
      - API_KEY=${API_KEY}
    depends_on:
      - whatsapp-api
    command: >
      sh -c "node dist/main.js \
        --mode mcp \
        --transport sse \
        --sse-port 5002 \
        --api-base-url http://whatsapp-api:5001/api \
        --api-key ${API_KEY}"
    ports:
      - "5002:5002"
    volumes:
      - whatsapp_api_auth:/app/.wwebjs_auth
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  whatsapp_api_auth:

networks:
  dokploy-network:
