version: '3.8'

services:
  whatsapp-api:
    image: ghcr.io/peter-hanzo/wweb-mcp:latest
    container_name: whatsapp-api
    environment:
      - MODE=whatsapp-api              # исправлено: совпадает с Dockerfile
      - API_PORT=${API_PORT:-5001}     # порт с дефолтом 5001
      - API_KEY=${API_KEY}
    ports:
      - "${API_PORT:-5001}:${API_PORT:-5001}"
    volumes:
      - whatsapp_api_auth:/app/.wwebjs_auth  # для сохранения сессии и QR-кода
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT:-5001}/api/health"] 
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - dokploy-network

  whatsapp-mcp:
    image: ghcr.io/peter-hanzo/wweb-mcp:latest
    container_name: whatsapp-mcp
    environment:
      - MODE=mcp
      - TRANSPORT=${TRANSPORT:-sse}
      - SSE_PORT=${SSE_PORT:-5002}
      - API_BASE_URL=http://whatsapp-api:${API_PORT:-5001}/api
      - API_KEY=${API_KEY}
    ports:
      - "${SSE_PORT:-5002}:${SSE_PORT:-5002}"
    depends_on:
      whatsapp-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  whatsapp_api_auth:

networks:
  dokploy-network:
    driver: bridge
