version: '3.8'

services:
  whatsapp-api:
    image: ghcr.io/peter-hanzo/wweb-mcp@sha256:597e473cdcc0b7333d7fd0c4b79a6670c1beb40087ef8de8c3e7b79372e3cd36
    container_name: whatsapp-api
    environment:
      - MODE=api               # <-- режим API
      - API_PORT=${API_PORT}
      - API_KEY=${API_KEY}
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    networks:
      - dokploy-network

  whatsapp-mcp:
    image: ghcr.io/peter-hanzo/wweb-mcp@sha256:597e473cdcc0b7333d7fd0c4b79a6670c1beb40087ef8de8c3e7b79372e3cd36
    container_name: whatsapp-mcp
    environment:
      - MODE=mcp               # <-- режим MCP
      - TRANSPORT=${TRANSPORT}
      - SSE_PORT=${SSE_PORT}
      - API_BASE_URL=http://whatsapp-api:${API_PORT}/api
      - API_KEY=${API_KEY}
    ports:
      - "${SSE_PORT}:${SSE_PORT}"
    restart: unless-stopped
    depends_on:
      - whatsapp-api
    networks:
      - dokploy-network

networks:
  dokploy-network:
    driver: bridge
